frontend/src/App.js
Before the hover was handled by just using the setUseState. I created a handle function that adds the necessary, pre-existing functions that fetch the project data from the CSV.
=> KEH-550 - Fix hover blip not showing projects

backend/package-lock.json, backend/package.json, backend/src/config/logger.js, backend/src/index.js, terraform/service/main.tf
**Important:** Merge into `projects-feature` branch. Therefore [pull request 5](https://github.com/ONS-Innovation/keh-digital-landscape/pull/5) relies on this pull request.
Although it seems to log consistently with just` console.log`, I have added the Winston functionality as described in the comment and ticket.
Terraform was adjusted with the Cloudwatch environment variable.
=> [KEH-562] - Log when backend is hit

terraform/service/iam.tf
Winston wasn't able to create logs as the policy hadn't been updated. I've added the policy in TF to allow this.
=> winston unable to access log group

frontend/src/pages/HomePage.js, frontend/src/styles/HomePage.css, terraform/authentication/main.tf, terraform/authentication/outputs.tf, terraform/service/alb.tf, terraform/service/main.tf
- Basically just removing and renaming a lot.
- Replaced the second cognito with the first cognito and removed the other one.
- Redployed to dev and prod :)
This is merging into the admin-dash branch as then once I have fully merged all into main, I can redeploy to prod.
=> [KEH-684] - Remove Cognito

frontend/src/components/Header/Header.js, frontend/src/components/MenuDropdown/MenuDropdown.js, frontend/src/components/Projects/Projects.js, frontend/src/components/Statistics/Skeletons/SkeletonStatCard.js, frontend/src/components/Statistics/Statistics.js, frontend/src/components/ThemeToggle/ThemeToggle.js, frontend/src/pages/ProjectsPage.js, frontend/src/pages/RadarPage.js, frontend/src/pages/ReviewPage.js, frontend/src/pages/StatisticsPage.js, frontend/src/styles/App.css, frontend/src/styles/HomePage.css, frontend/src/styles/ProjectsPage.css, frontend/src/styles/ReviewPage.css, frontend/src/styles/StatisticsPage.css, frontend/src/styles/components/Header.css, frontend/src/styles/components/MenuDropdown.css, frontend/src/styles/components/MultiSelect.css, frontend/src/styles/components/ProjectModal.css, frontend/src/styles/components/Projects.css, frontend/src/styles/components/Statistics.css, frontend/src/styles/components/ThemeToggle.css, frontend/src/styles/index.css
for demo, merging all changes in temp branch
=> merge update-header into temp-demo

frontend/src/components/Header/HelpModal.js, frontend/src/pages/RadarPage.js, frontend/src/styles/App.css
click the labels to filter the radar
more logic added to the calculateBlipPosition function
=> [KEH-693] - Filter radar view by clicking on quadrant boxes

frontend/src/components/Statistics/Statistics.js
Review and Ignore tech shown on Statistics page.
=> review and ignore show up on statistics page

backend/src/index.js, frontend/src/components/Header/Header.js, frontend/src/components/Projects/Projects.js, frontend/src/components/Statistics/Statistics.js, frontend/src/contexts/dataContext.js, frontend/src/index.js, frontend/src/pages/ProjectsPage.js, frontend/src/pages/RadarPage.js, frontend/src/pages/StatisticsPage.js, frontend/src/styles/components/Projects.css, frontend/src/utilities/getCSVData.js, frontend/src/utilities/getRepositoryData.js, frontend/src/utilities/getTechRadarJson.js
Aim:
- Reduce number of useless API calls
- Increase loading speeds between pages
Main changes:
- Changed links in header to use <Link /> as then state is maintained between pages
- Created dataContext and multiple getData functions using useData()
- Prevents duplication using pendingRequests
Extra:
- Only allow multi-select for GitHub repos with `github.com/ONSdigital`
Notes:
- The review page is linked in the header with an `<a>` tag meaning the state will be refreshed when loading onto that page. 
- That is because on the deployed version, if a user navigates to the review page a `<Link>` then the state isn't refreshed and they are not prompted to log into Cognito.
=> KEH-706 - Client-side caching with useContext()

frontend/src/pages/ReviewPage.js, frontend/src/styles/ReviewPage.css
Closing old PR:
https://github.com/ONS-Innovation/keh-digital-landscape/pull/31
=> KEH-716 - Duplication bug 2nd option

backend/src/utilities/projectDataTransformer.js, frontend/src/components/Projects/ProjectModal.js, frontend/src/pages/ProjectsPage.js, frontend/src/styles/components/ProjectModal.css
- Click to open or close accordion
- Programme and programme short name has not been added TAT side but the backend will return just `""` instead meaning it is ready for TAT as long as we save it as `programme_name` and `programme_short_name`.
- Description is shown.
- We record documentation link as just one link on TAT side, but it is stored as a list of strings so we have possibility to store multiple doc links.
=> KEH-738 - Project modal accordion

backend/src/utilities/projectDataTransformer.js, frontend/src/pages/ReviewPage.js
- [csv return null caused error](https://github.com/ONS-Innovation/keh-digital-landscape/commit/b01b38e9b38cf21d505ca1d842dde5f9d2ed80ff) - on dev we are submitting projects with empty fields so this now checks whether they are null and will return "" if so.
- [add more fields to check](https://github.com/ONS-Innovation/keh-digital-landscape/commit/3026e307f73e3f0488c5802b7fe7e54f2c13fa9b) - update the fields to check when comparing json file to csv on review page
- [rm error causing non existent function](https://github.com/ONS-Innovation/keh-digital-landscape/commit/7b13d8c7a6a85110745ac6b1d085f8537335c9a1) - on prod this was causing a 'setProjectData' is not defined. Not sure why it was added in as setProjectData is not defined as a prop or function on any other major page.
=> Update review scan bugs

frontend/src/components/Header/HelpModal.js, frontend/src/styles/components/HelpModal.css
- Minor css changes
- Added doc link to every modal
=> KEH-768 - Add GitHub pages doc link to top of help modal

frontend/src/pages/ReviewPage.js, frontend/src/styles/ReviewPage.css, mkdocs/docs/pages/review/index.md
I removed all technologies that had been added to the review but hadn't been moved onto the radar.
The new ScanForNewTechnologies compares old and new both as lowercase so now it's not case sensitive meaning
'S3 **b**ucket' and 'S3 **B**ucket' will just be shown as whichever was first in the list.
An admin can then change the case (lower/upper) if needed.
Updated docs for these changes too.
=> KEH-823 - ScanForNewTechnologies is not case sensitive

.github/pull_request_template.md
=> KEH-PR-Template

.github/workflows/deploy_mkdocs.yml
=> MkDocs Action Patch 1

.github/workflows/deploy_mkdocs.yml
Fix reference to `mkdocs_requirements.txt` within the `deploy_mkdocs` action.
=> MkDocs Action Patch 2

.github/workflows/deploy_mkdocs.yml
`cd` into `mkdocs` before running `gh-deploy`
=> MkDocs Action Patch 3

.github/workflows/deploy_mkdocs.yml, mkdocs/Makefile
Add PYTHONPATH to command so it can find python files at the root of the repo
=> mkdocs action patch 4

frontend/src/pages/ReviewPage.js
Extension of this PR #61.
Same fix but for the ReviewPage.
=> KEH-914 - PATCH - Add project tech check to Review

mkdocs/docs/components/admin/bannerManagement.md, mkdocs/docs/components/admin/techManagement.md, mkdocs/docs/documentation.md, mkdocs/docs/index.md, mkdocs/docs/pages/admin/index.md, mkdocs/docs/testing/backend.md, mkdocs/mkdocs.yml
Added the documentation for the admin page.
Original PR (#63)
See /mkdocs/README.md
=> KEH-832 - Add Admin page docs to MkDocs

frontend/src/components/Projects/ProjectModal.js, frontend/src/styles/components/ProjectModal.css
Each section is now a collapsible accordion.
~~Provide links to any related issues.~~
- make dev
- view /projects
- click on a project
- view project modal and play with accordions
=> KEH-963 - Set group title and repositories as collapsible accordions

frontend/src/components/CoPilot/Dashboards/LiveDashboard.js
KEH-880 merge mistakenly did a length check on pie charts and breakdowns data which have keys, so they were not rendered.
KEH-880
Check stats components are correctly rendered.
=> KEH-880 Patch

mkdocs/docs/testing/backend.md, mkdocs/mkdocs.yml
Fixed bug in mkdocs.yml file. Updated mkdocs with correct tests for copilot.
`cd mkdocs` then `make mkdocs` make sure it runs correctly, then view 
http://127.0.0.1:8000/testing/backend/#testing.backend.src.test_main.test_json_endpoint_no_params
[link](http://127.0.0.1:8000/testing/backend/#testing.backend.src.test_main.test_json_endpoint_no_params)
=> KEH-880-PATCH-2 - Fix mkdocs test_copilot docs

frontend/src/components/Header/HelpModal.js
Add link to the tech radar submission repository for users to submit new technology to the radar.
`make dev` then view the homepage localhost:3000/ and click the help button at the bottom of the sidebar
=> KEH-1123 - Add submissionRepoLink and add docstrings

frontend/src/utilities/markdownRenderer.js
Minor update to fix spacing in markdown. Not on dev yet. Pull down and run locally to view changes.
=> Update markdown to fix vertical spacing and line breaks

frontend/src/components/Header/HelpModal.js, frontend/src/styles/components/HelpModal.css
Update the helper modal appearance.
Provide links to any related issues.
Describe the steps required to test the changes.
=> Keh 1314 update helper modal
